version: '3.9'

services:
  database:
    image: 'postgres'
    container_name: citybike-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: citybike
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data/
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  dbdata:
    driver: local
  pgadmin_data:
