version: "3.9"

services:
  database:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: citybike_test
    ports:
      - 7654:5432
    volumes:
      - dbdata:/var/lib/postgresql/data/
      - ./src/db/testdbinit.sql:/docker-entrypoint-initdb.d/testdbinit.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  dbdata:
    driver: local
  pgadmin_data:
