version: '3.9'

services:
  database:
    image: 'postgres'
    restart: always
    container_name: citybike-db-test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: citybike_test
    ports:
      - 6543:5432
    volumes:
      - ./src/db/testdbinit.sql:/docker-entrypoint-initdb.d/01_testdbinit.sql
      - ./src/tests/data/import_data.sql:/docker-entrypoint-initdb.d/02_import_data.sql
      - ./src/tests/data:/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password

volumes:
  testdata:
    driver: local
  pgadmin_data:
